// <auto-generated />
namespace procesos_app.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FixingSubjectPrerequisitswithcareer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixingSubjectPrerequisitswithcareer));
        
        string IMigrationMetadata.Id
        {
            get { return "201707061532432_Fixing Subject Prerequisits with career"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
